repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ "--maxkb=1492" ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: >
          (?x)^(
              .*\.css|
              .*\.js|
              \.tox
          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        exclude: >
          (?x)^(
              .*\.jinja.py|
          )$

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [ "--config", "pyproject.toml", "--target-version", "py310" ]
        exclude: >
          (?x)^(
              .*\.jinja.py|
          )$

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

  - repo: https://github.com/nrbnlulu/qt-hooks
    rev: v0.1.5
    hooks:
      - id: qml-format
